name: Start server

on:
  workflow_dispatch:

jobs:
  start-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: npm i

      - run: |
          sudo snap install ngrok --devmode
          sudo ngrok config add-authtoken ${{secrets.NGROK_AUTH_TOKEN}}
          ls -la
          ./ngrok http ${{secrets.PORT}}

      - run: node api/base-api.js
        id: start-server
        timeout-minutes: 1
        continue-on-error: true
        env:
          PORT: ${{secrets.PORT}}
          BASE_URL: ${{secrets.BASE_URL}}
          SWAGGER_URL: ${{secrets.SWAGGER_URL}}
