name: Start server
on: [push]

jobs:
  start-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Print Public IP
        run: |
          echo ${{ steps.ip.outputs.ipv4 }}
          echo ${{ steps.ip.outputs.ipv6 }}

      - run: npm i

      - run: node api/base-api.js
        id: start-server
        timeout-minutes: 10
        continue-on-error: true
        env:
          PORT: ${{secrets.PORT}}
          BASE_URL: ${{secrets.BASE_URL}}
          SWAGGER_URL: ${{secrets.SWAGGER_URL}}
